export { default as Home } from './Home'
export { default as Login } from './Login'
export { default as Register } from './Register'
export { default as Error } from './Error'
export { default as SingleProduct} from './SingleProduct'
export { default as Store } from './Store'
export { default as Todos } from './Todos'